development:
  adapter: postgresql
  database: stuff
  username: postgres
  password: pass000
  host: localhost
  encoding: UTF8

test:
  adapter: postgresql
  database: stuff-test
  username: postgres
  password: pass000
  host: localhost
  encoding: UTF8

production:
  adapter: postgresql
  database: d513g9k39si85e
  username: svqnuueodrdfvu
  password: vxx-nZUeANbQkyoizo4E9vMJHl
  host: ec2-54-163-226-155.compute-1.amazonaws.com
